### PR TITLE
Narrow Message Types being passed into SubmitCallback or GetCallback

### LINKED ISSUE #151: Narrow Message Types being passed into SubmitCallback or GetCallback
Discord Thread: https://discord.com/channels/937858703112155166/949067728709369856/1204494465541210162
JS PR: https://github.com/TBD54566975/tbdex-js/pull/156/files#diff-fe3b59c637fcb3e6e3b01742b42b35cb58e2160f60310da6d9fc1085ba5a4be3R21

Right now it isn't smooth to convert from a `Message` to one of its subtypes like `Rfq` from a dev standpoint. If for example you're writing your `SubmitCallback` and pass through your message, in the callback you'll need to write something similar to this:

```kotlin
val message: Rfq?

  try {
    message = Message.parse(call.receiveText()) as Rfq
  } catch (e: Exception) {
    val errorDetail = ErrorDetail(detail = "Parsing of TBDex message failed: ${e.message}")
    val errorResponse = ErrorResponse(listOf(errorDetail))
    call.respond(HttpStatusCode.BadRequest, errorResponse)
    return
  }
```

Ideally I think it'd be a better dev experience to have a convenience method that removes the optionality and looks something like:

```kotlin
val rfq = Rfq.from(message = message)
```

If that method could handle the optionality internally to avoid exposing any of that to devs I think it'd make for a better user experience.

### PR DESCRIPTION
**Pull request by jiyoontbd**
closes #151 

also removes GetOfferingFilter re: https://github.com/TBD54566975/tbdex/pull/302

also changes `ExchangeApi.getExchange()`(singular) to pass in `requesterDid`

### CODE REVIEW

File: httpserver/src/main/kotlin/tbdex/sdk/httpserver/TestServer.kt
Comment (jiyoontbd) [inline httpserver/src/main/kotlin/tbdex/sdk/httpserver/TestServer.kt:1]: reminder to myself to remove this before merging

File: httpserver/src/main/kotlin/tbdex/sdk/httpserver/handlers/GetOfferings.kt [hunk 1]
```diff
@@ -48,7 +48,7 @@ suspend fun getOfferings(
     // copied from httpserver-js
     // TODO: figure out what to do with callback result. should we pass through the offerings we've fetched
     // and allow the callback to modify what's returned? (issue #11)
-    callback.invoke(call, queryParams)
```
Comment (jiyoontbd) [inline httpserver/src/main/kotlin/tbdex/sdk/httpserver/handlers/GetOfferings.kt:51]: we're removing offering queryparams

File: httpserver/src/main/kotlin/tbdex/sdk/httpserver/handlers/SubmitMessage.kt [hunk 2]
```diff
@@ -25,7 +26,7 @@ import tbdex.sdk.protocol.models.Order
 suspend fun submitMessage(
   call: ApplicationCall,
   exchangesApi: ExchangesApi,
-  callback: SubmitCallback?
+  callback: Any?
```
Comment (jiyoontbd) [inline httpserver/src/main/kotlin/tbdex/sdk/httpserver/handlers/SubmitMessage.kt:29]: don't want to here as `Any` :/

File: httpserver/src/main/kotlin/tbdex/sdk/httpserver/handlers/GetExchange.kt [hunk 3]
```diff
@@ -88,7 +87,7 @@ suspend fun getExchange(
   if (callback != null) {
     // TODO: figure out what to do with callback result. should we pass through the exchanges we've fetched
     //       and allow the callback to modify what's returned? (issue #10)
-    val result = callback.invoke(call, GetExchangesFilter())
```
Comment (jiyoontbd) [inline httpserver/src/main/kotlin/tbdex/sdk/httpserver/handlers/GetExchange.kt:91]: i don't think we need to pass in a filter for get single exchange since that's only asking for 1 exchange

File: httpserver/src/main/kotlin/tbdex/sdk/httpserver/TestServer.kt [hunk 4]
```diff
@@ -0,0 +1,70 @@
...
+  val serverConfig = TbdexHttpServerConfig(
+    port = 8080,
+    pfiDid = DidDht.create(InMemoryKeyManager()).uri,
+    offeringsApi = FakeOfferingsApi(),
+    exchangesApi = FakeExchangesApi()
+  )
+
+  val tbdexServer = TbdexHttpServer(serverConfig)
+
+  tbdexServer.createExchange { call, rfq, offering, replyTo ->
```
Comment (jiyoontbd) [inline httpserver/src/main/kotlin/tbdex/sdk/httpserver/TestServer.kt:27]: fyi @chris-tbd this is how i imagine you could implement the server once this change is actually implemented. much nicer, imo, and hopefully solves the problem you meant to address when you wrote issue #151 

please let me know if u have any questions

Comment (jiyoontbd) [reply httpserver/src/main/kotlin/tbdex/sdk/httpserver/TestServer.kt:27]: Cc @angiejones

File: httpserver/src/main/kotlin/tbdex/sdk/httpserver/TbdexHttpServer.kt [hunk 5]
```diff
@@ -69,8 +68,8 @@ class TbdexHttpServerConfig(
  * @property config The configuration for the server, including port and optional APIs.
  */
 class TbdexHttpServer(val config: TbdexHttpServerConfig) {
-  val getCallbacks: MutableMap<String, GetCallback> = mutableMapOf()
-  val submitCallbacks: MutableMap<String, SubmitCallback> = mutableMapOf()
+  // todo i don't want to use Any :/
```
Comment (chris-tbd) [inline httpserver/src/main/kotlin/tbdex/sdk/httpserver/TbdexHttpServer.kt:71]: Is this a placeholder that's going to get solved in this PR or a future one?

File: httpserver/src/main/kotlin/tbdex/sdk/httpserver/TbdexHttpServer.kt [hunk 6]
```diff
@@ -134,36 +134,74 @@ class TbdexHttpServer(val config: TbdexHttpServerConfig) {
...
   }
 
   /**
-   * Adds a submit callback for a specific message kind (RFQ, order, close, etc.).
+   * Adds a GetOfferingsCallback for handling requests for offerings.
+   *
+   * @param callback GetOfferingsCallback function to be registered
+   */
+  fun getOfferings(callback: GetOfferingsCallback) {
+    this.callbacks["offerings"] = callback
```
Comment (chris-tbd) [inline httpserver/src/main/kotlin/tbdex/sdk/httpserver/TbdexHttpServer.kt:159]: can we offer these string literals as an enum or something to avoid any errors and expose them to the client if needed?

File: httpserver/src/main/kotlin/tbdex/sdk/httpserver/TbdexHttpServer.kt [hunk 7]
```diff
@@ -99,33 +98,34 @@ class TbdexHttpServer(val config: TbdexHttpServerConfig) {
...
 
+      // todo i don't want do unchecked cast here
       route("/exchanges") {
         post {
           createExchange(
             call = call,
             offeringsApi = offeringsApi,
             exchangesApi = exchangesApi,
-            callback = submitCallbacks.getOrDefault("rfq", null)
+            callback = callbacks.getOrDefault("rfq", null) as CreateExchangeCallback?
```
Comment (chris-tbd) [inline httpserver/src/main/kotlin/tbdex/sdk/httpserver/TbdexHttpServer.kt:112]: Rather than having an array of callbacks (since we only have one implementation of each) should we just have them each typed out as their own var?

File: httpserver/src/main/kotlin/tbdex/sdk/httpserver/TbdexHttpServer.kt [hunk 8]
```diff
@@ -134,36 +134,74 @@ class TbdexHttpServer(val config: TbdexHttpServerConfig) {
...
     }
   }
 
   /**
-   * Adds a submit callback for a specific message kind (RFQ, order, close, etc.).
+   * Adds a GetOfferingsCallback for handling requests for offerings.
+   *
+   * @param callback GetOfferingsCallback function to be registered
+   */
+  fun getOfferings(callback: GetOfferingsCallback) {
```
Comment (chris-tbd) [inline httpserver/src/main/kotlin/tbdex/sdk/httpserver/TbdexHttpServer.kt:158]: I think it may be clearer (but maybe not Kotlin-y) to change the names of these functions to `onGetOfferings()` etc.

File: httpserver/src/main/kotlin/tbdex/sdk/httpserver/TestServer.kt (hunk 4 above)
Comment (chris-tbd) [reply httpserver/src/main/kotlin/tbdex/sdk/httpserver/TestServer.kt:27]: Love this way of handling it!

File: httpserver/src/main/kotlin/tbdex/sdk/httpserver/TbdexHttpServer.kt (hunk 5 above)
Comment (jiyoontbd) [reply httpserver/src/main/kotlin/tbdex/sdk/httpserver/TbdexHttpServer.kt]: this PR - just solved it with help from @diehuxx  :)

File: httpserver/src/main/kotlin/tbdex/sdk/httpserver/TbdexHttpServer.kt (hunk 6 above)
Comment (jiyoontbd) [reply httpserver/src/main/kotlin/tbdex/sdk/httpserver/TbdexHttpServer.kt]: now using Callback class and variables housed inside https://github.com/TBD54566975/tbdex-kt/pull/218/commits/7d819ff3f7d79697cf1a80cc87ebdb459c2a8af1

File: httpserver/src/main/kotlin/tbdex/sdk/httpserver/TbdexHttpServer.kt (hunk 7 above)
Comment (jiyoontbd) [reply httpserver/src/main/kotlin/tbdex/sdk/httpserver/TbdexHttpServer.kt]: see https://github.com/TBD54566975/tbdex-kt/pull/218#discussion_r1544832930

File: httpserver/src/main/kotlin/tbdex/sdk/httpserver/TbdexHttpServer.kt (hunk 8 above)
Comment (jiyoontbd) [reply httpserver/src/main/kotlin/tbdex/sdk/httpserver/TbdexHttpServer.kt:159]: hmm, so you'd prefer

```kt
  tbdexServer.onGetOfferings { call ->
    println("Getting offerings...")
    call.respond(HttpStatusCode.OK, listOf<Offering>())
  }
```

over

```kt
  tbdexServer.getOfferings { call ->
    println("Getting offerings...")
    call.respond(HttpStatusCode.OK, listOf<Offering>())
  }
```

?

File: httpserver/src/main/kotlin/tbdex/sdk/httpserver/TestServer.kt (hunk 4 above)
Comment (jiyoontbd) [reply httpserver/src/main/kotlin/tbdex/sdk/httpserver/TestServer.kt:27]: now type checking is redundant 🎉 
image

File: httpserver/src/main/kotlin/tbdex/sdk/httpserver/TbdexHttpServer.kt (hunk 8 above)
Comment (diehuxx) [reply httpserver/src/main/kotlin/tbdex/sdk/httpserver/TbdexHttpServer.kt:159]: @jiyoontbd Personally I also like `tbdexServer.onGetOfferings`, but it doesn't matter too much either way. I trust your judgement

File: httpserver/src/main/kotlin/tbdex/sdk/httpserver/handlers/CreateExchange.kt [hunk 9]
```diff
@@ -32,17 +32,17 @@ suspend fun createExchange(
...
+  val rfq: Rfq?
   var replyTo: String? = null
   try {
     val requestBody = call.receiveText()
 
     val jsonNode = Json.jsonMapper.readTree(requestBody)
     val rfqJsonString = jsonNode["rfq"].toString()
 
-    message = Message.parse(rfqJsonString) as Rfq
+    rfq = Message.parse(rfqJsonString) as Rfq
```
Comment (diehuxx) [inline httpserver/src/main/kotlin/tbdex/sdk/httpserver/handlers/CreateExchange.kt:45]:
```suggestion
    rfq = Message.parse(rfqJsonString)
```

**Review by diehuxx — APPROVED** [review]
this looks slick. way nicer DX. lgtm, pending removal of `TestServer.kt` of course

File: httpserver/src/main/kotlin/tbdex/sdk/httpserver/TbdexHttpServer.kt (hunk 8 above)
Comment (jiyoontbd) [reply httpserver/src/main/kotlin/tbdex/sdk/httpserver/TbdexHttpServer.kt]: actually, i think i will do `on...` because else i keep confusing it with the handler methods which have the same names. fixed in https://github.com/TBD54566975/tbdex-kt/pull/218/commits/ab8de7e473890207bbc95a3a0b9a42c279a4ca59

**Comment by jiyoontbd** [comment]
@kirahsapong thanks for the reminder! i've gone ahead and written _most_ tests to ensure callbacks are being invoked etc. there were a couple i could not get to work, and i've outlined that work in https://github.com/TBD54566975/tbdex-kt/issues/223 no changes to existing tests were needed.

**Comment by jiyoontbd** [comment]
> also changes `ExchangeApi.getExchange()` (singular) to pass in `requesterDid`

cc @chris-tbd - `ExchangesApi.getExchanges()` (plural) had required one to pass in requesterDid. in this PR, we are now also requiring requesterDid to be passed in the call to get a single exchange.
